apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeshield.fullname" . }}
  labels:
    {{- include "kubeshield.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubeshield.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubeshield.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: kubeshield
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.secretEnv }}
          envFrom:
            - secretRef:
                name: {{ (index . 0).secretRef }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /app/data
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if .Values.volumes.data.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "kubeshield.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
