{{- if .Values.volumes.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubeshield.fullname" . }}
  labels:
    {{- include "kubeshield.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.data.size }}
  {{- if .Values.volumes.data.storageClass }}
  storageClassName: {{ .Values.volumes.data.storageClass }}
  {{- end }}
{{- end }}
